export enum SystemUserLevel {
  DIVITIONAL_ADMIN = "DIVITIONAL_ADMIN",
  BEAT_OFFICER = "BEAT_OFFICER",
  NATIONAL_DEPARTMENT_ADMIN = "NATIONAL_DEPARTMENT_ADMIN",
  NATIONAL_ADMIN = "NATIONAL_ADMIN",
}
